package mitre

// Code generated from MITRE ATT&CK Enterprise STIX data; DO NOT EDIT.
// Source: https://github.com/mitre-attack/attack-stix-data/tree/master/enterprise-attack
// Bundle SHA-256: bdf1ce86a4e604214c5076d37ae4dcb322678afc528df8492e6fdc1b554f5da3
// Bundle latest attack-pattern modified timestamp: 2026-05-12T15:12:00.727Z

var techniques = map[string]Technique{
	"T1001":     {Name: "Data Obfuscation", Tactics: []string{"command-and-control"}},
	"T1001.001": {Name: "Junk Data", Tactics: []string{"command-and-control"}},
	"T1001.002": {Name: "Steganography", Tactics: []string{"command-and-control"}},
	"T1001.003": {Name: "Protocol or Service Impersonation", Tactics: []string{"command-and-control"}},
	"T1002":     {Name: "Data Compressed", Tactics: []string{"exfiltration"}, Revoked: true, Replacement: "T1560"},
	"T1003":     {Name: "OS Credential Dumping", Tactics: []string{"credential-access"}},
	"T1003.001": {Name: "LSASS Memory", Tactics: []string{"credential-access"}},
	"T1003.002": {Name: "Security Account Manager", Tactics: []string{"credential-access"}},
	"T1003.003": {Name: "NTDS", Tactics: []string{"credential-access"}},
	"T1003.004": {Name: "LSA Secrets", Tactics: []string{"credential-access"}},
	"T1003.005": {Name: "Cached Domain Credentials", Tactics: []string{"credential-access"}},
	"T1003.006": {Name: "DCSync", Tactics: []string{"credential-access"}},
	"T1003.007": {Name: "Proc Filesystem", Tactics: []string{"credential-access"}},
	"T1003.008": {Name: "/etc/passwd and /etc/shadow", Tactics: []string{"credential-access"}},
	"T1004":     {Name: "Winlogon Helper DLL", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.004"},
	"T1005":     {Name: "Data from Local System", Tactics: []string{"collection"}},
	"T1006":     {Name: "Direct Volume Access", Tactics: []string{"stealth"}},
	"T1007":     {Name: "System Service Discovery", Tactics: []string{"discovery"}},
	"T1008":     {Name: "Fallback Channels", Tactics: []string{"command-and-control"}},
	"T1009":     {Name: "Binary Padding", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1027.001"},
	"T1010":     {Name: "Application Window Discovery", Tactics: []string{"discovery"}},
	"T1011":     {Name: "Exfiltration Over Other Network Medium", Tactics: []string{"exfiltration"}},
	"T1011.001": {Name: "Exfiltration Over Bluetooth", Tactics: []string{"exfiltration"}},
	"T1012":     {Name: "Query Registry", Tactics: []string{"discovery"}},
	"T1013":     {Name: "Port Monitors", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1547.010"},
	"T1014":     {Name: "Rootkit", Tactics: []string{"stealth"}},
	"T1015":     {Name: "Accessibility Features", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1546.008"},
	"T1016":     {Name: "System Network Configuration Discovery", Tactics: []string{"discovery"}},
	"T1016.001": {Name: "Internet Connection Discovery", Tactics: []string{"discovery"}},
	"T1016.002": {Name: "Wi-Fi Discovery", Tactics: []string{"discovery"}},
	"T1017":     {Name: "Application Deployment Software", Tactics: []string{"lateral-movement"}, Revoked: true, Replacement: "T1072"},
	"T1018":     {Name: "Remote System Discovery", Tactics: []string{"discovery"}},
	"T1019":     {Name: "System Firmware", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1542.001"},
	"T1020":     {Name: "Automated Exfiltration", Tactics: []string{"exfiltration"}},
	"T1020.001": {Name: "Traffic Duplication", Tactics: []string{"exfiltration"}},
	"T1021":     {Name: "Remote Services", Tactics: []string{"lateral-movement"}},
	"T1021.001": {Name: "Remote Desktop Protocol", Tactics: []string{"lateral-movement"}},
	"T1021.002": {Name: "SMB/Windows Admin Shares", Tactics: []string{"lateral-movement"}},
	"T1021.003": {Name: "Distributed Component Object Model", Tactics: []string{"lateral-movement"}},
	"T1021.004": {Name: "SSH", Tactics: []string{"lateral-movement"}},
	"T1021.005": {Name: "VNC", Tactics: []string{"lateral-movement"}},
	"T1021.006": {Name: "Windows Remote Management", Tactics: []string{"lateral-movement"}},
	"T1021.007": {Name: "Cloud Services", Tactics: []string{"lateral-movement"}},
	"T1021.008": {Name: "Direct Cloud VM Connections", Tactics: []string{"lateral-movement"}},
	"T1022":     {Name: "Data Encrypted", Tactics: []string{"exfiltration"}, Revoked: true, Replacement: "T1560"},
	"T1023":     {Name: "Shortcut Modification", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.009"},
	"T1024":     {Name: "Custom Cryptographic Protocol", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1573"},
	"T1025":     {Name: "Data from Removable Media", Tactics: []string{"collection"}},
	"T1026":     {Name: "Multiband Communication", Tactics: []string{"command-and-control"}, Deprecated: true},
	"T1027":     {Name: "Obfuscated Files or Information", Tactics: []string{"stealth"}},
	"T1027.001": {Name: "Binary Padding", Tactics: []string{"stealth"}},
	"T1027.002": {Name: "Software Packing", Tactics: []string{"stealth"}},
	"T1027.003": {Name: "Steganography", Tactics: []string{"stealth"}},
	"T1027.004": {Name: "Compile After Delivery", Tactics: []string{"stealth"}},
	"T1027.005": {Name: "Indicator Removal from Tools", Tactics: []string{"stealth"}},
	"T1027.006": {Name: "HTML Smuggling", Tactics: []string{"stealth"}},
	"T1027.007": {Name: "Dynamic API Resolution", Tactics: []string{"stealth"}},
	"T1027.008": {Name: "Stripped Payloads", Tactics: []string{"stealth"}},
	"T1027.009": {Name: "Embedded Payloads", Tactics: []string{"stealth"}},
	"T1027.010": {Name: "Command Obfuscation", Tactics: []string{"stealth"}},
	"T1027.011": {Name: "Fileless Storage", Tactics: []string{"stealth"}},
	"T1027.012": {Name: "LNK Icon Smuggling", Tactics: []string{"stealth"}},
	"T1027.013": {Name: "Encrypted/Encoded File", Tactics: []string{"stealth"}},
	"T1027.014": {Name: "Polymorphic Code", Tactics: []string{"stealth"}},
	"T1027.015": {Name: "Compression", Tactics: []string{"stealth"}},
	"T1027.016": {Name: "Junk Code Insertion", Tactics: []string{"stealth"}},
	"T1027.017": {Name: "SVG Smuggling", Tactics: []string{"stealth"}},
	"T1027.018": {Name: "Invisible Unicode", Tactics: []string{"stealth"}},
	"T1028":     {Name: "Windows Remote Management", Tactics: []string{"execution", "lateral-movement"}, Revoked: true, Replacement: "T1021.006"},
	"T1029":     {Name: "Scheduled Transfer", Tactics: []string{"exfiltration"}},
	"T1030":     {Name: "Data Transfer Size Limits", Tactics: []string{"exfiltration"}},
	"T1031":     {Name: "Modify Existing Service", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1543.003"},
	"T1032":     {Name: "Standard Cryptographic Protocol", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1573"},
	"T1033":     {Name: "System Owner/User Discovery", Tactics: []string{"discovery"}},
	"T1034":     {Name: "Path Interception", Tactics: []string{"persistence", "privilege-escalation"}, Deprecated: true},
	"T1035":     {Name: "Service Execution", Tactics: []string{"execution"}, Revoked: true, Replacement: "T1569.002"},
	"T1036":     {Name: "Masquerading", Tactics: []string{"stealth"}},
	"T1036.001": {Name: "Invalid Code Signature", Tactics: []string{"stealth"}},
	"T1036.002": {Name: "Right-to-Left Override", Tactics: []string{"stealth"}},
	"T1036.003": {Name: "Rename Legitimate Utilities", Tactics: []string{"stealth"}},
	"T1036.004": {Name: "Masquerade Task or Service", Tactics: []string{"stealth"}},
	"T1036.005": {Name: "Match Legitimate Resource Name or Location", Tactics: []string{"stealth"}},
	"T1036.006": {Name: "Space after Filename", Tactics: []string{"stealth"}},
	"T1036.007": {Name: "Double File Extension", Tactics: []string{"stealth"}},
	"T1036.008": {Name: "Masquerade File Type", Tactics: []string{"stealth"}},
	"T1036.009": {Name: "Break Process Trees", Tactics: []string{"stealth"}},
	"T1036.010": {Name: "Masquerade Account Name", Tactics: []string{"stealth"}},
	"T1036.011": {Name: "Overwrite Process Arguments", Tactics: []string{"stealth"}},
	"T1036.012": {Name: "Browser Fingerprint", Tactics: []string{"stealth"}},
	"T1037":     {Name: "Boot or Logon Initialization Scripts", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1037.001": {Name: "Logon Script (Windows)", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1037.002": {Name: "Login Hook", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1037.003": {Name: "Network Logon Script", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1037.004": {Name: "RC Scripts", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1037.005": {Name: "Startup Items", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1038":     {Name: "DLL Search Order Hijacking", Tactics: []string{"persistence", "privilege-escalation", "stealth"}, Revoked: true, Replacement: "T1574.001"},
	"T1039":     {Name: "Data from Network Shared Drive", Tactics: []string{"collection"}},
	"T1040":     {Name: "Network Sniffing", Tactics: []string{"credential-access", "discovery"}},
	"T1041":     {Name: "Exfiltration Over C2 Channel", Tactics: []string{"exfiltration"}},
	"T1042":     {Name: "Change Default File Association", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1546.001"},
	"T1043":     {Name: "Commonly Used Port", Tactics: []string{"command-and-control"}, Deprecated: true},
	"T1044":     {Name: "File System Permissions Weakness", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1574.010"},
	"T1045":     {Name: "Software Packing", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1027.002"},
	"T1046":     {Name: "Network Service Discovery", Tactics: []string{"discovery"}},
	"T1047":     {Name: "Windows Management Instrumentation", Tactics: []string{"execution"}},
	"T1048":     {Name: "Exfiltration Over Alternative Protocol", Tactics: []string{"exfiltration"}},
	"T1048.001": {Name: "Exfiltration Over Symmetric Encrypted Non-C2 Protocol", Tactics: []string{"exfiltration"}},
	"T1048.002": {Name: "Exfiltration Over Asymmetric Encrypted Non-C2 Protocol", Tactics: []string{"exfiltration"}},
	"T1048.003": {Name: "Exfiltration Over Unencrypted Non-C2 Protocol", Tactics: []string{"exfiltration"}},
	"T1049":     {Name: "System Network Connections Discovery", Tactics: []string{"discovery"}},
	"T1050":     {Name: "New Service", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1543.003"},
	"T1051":     {Name: "Shared Webroot", Tactics: []string{"lateral-movement"}, Deprecated: true},
	"T1052":     {Name: "Exfiltration Over Physical Medium", Tactics: []string{"exfiltration"}},
	"T1052.001": {Name: "Exfiltration over USB", Tactics: []string{"exfiltration"}},
	"T1053":     {Name: "Scheduled Task/Job", Tactics: []string{"execution", "persistence", "privilege-escalation"}},
	"T1053.001": {Name: "At (Linux)", Tactics: []string{"execution", "persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1053.002"},
	"T1053.002": {Name: "At", Tactics: []string{"execution", "persistence", "privilege-escalation"}},
	"T1053.003": {Name: "Cron", Tactics: []string{"execution", "persistence", "privilege-escalation"}},
	"T1053.004": {Name: "Launchd", Tactics: []string{"execution", "persistence", "privilege-escalation"}, Deprecated: true},
	"T1053.005": {Name: "Scheduled Task", Tactics: []string{"execution", "persistence", "privilege-escalation"}},
	"T1053.006": {Name: "Systemd Timers", Tactics: []string{"execution", "persistence", "privilege-escalation"}},
	"T1053.007": {Name: "Container Orchestration Job", Tactics: []string{"execution", "persistence", "privilege-escalation"}},
	"T1054":     {Name: "Indicator Blocking", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685"},
	"T1055":     {Name: "Process Injection", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.001": {Name: "Dynamic-link Library Injection", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.002": {Name: "Portable Executable Injection", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.003": {Name: "Thread Execution Hijacking", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.004": {Name: "Asynchronous Procedure Call", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.005": {Name: "Thread Local Storage", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.008": {Name: "Ptrace System Calls", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.009": {Name: "Proc Memory", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.011": {Name: "Extra Window Memory Injection", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.012": {Name: "Process Hollowing", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.013": {Name: "Process Doppelgänging", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.014": {Name: "VDSO Hijacking", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1055.015": {Name: "ListPlanting", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1056":     {Name: "Input Capture", Tactics: []string{"collection", "credential-access"}},
	"T1056.001": {Name: "Keylogging", Tactics: []string{"collection", "credential-access"}},
	"T1056.002": {Name: "GUI Input Capture", Tactics: []string{"collection", "credential-access"}},
	"T1056.003": {Name: "Web Portal Capture", Tactics: []string{"collection", "credential-access"}},
	"T1056.004": {Name: "Credential API Hooking", Tactics: []string{"collection", "credential-access"}},
	"T1057":     {Name: "Process Discovery", Tactics: []string{"discovery"}},
	"T1058":     {Name: "Service Registry Permissions Weakness", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1574.011"},
	"T1059":     {Name: "Command and Scripting Interpreter", Tactics: []string{"execution"}},
	"T1059.001": {Name: "PowerShell", Tactics: []string{"execution"}},
	"T1059.002": {Name: "AppleScript", Tactics: []string{"execution"}},
	"T1059.003": {Name: "Windows Command Shell", Tactics: []string{"execution"}},
	"T1059.004": {Name: "Unix Shell", Tactics: []string{"execution"}},
	"T1059.005": {Name: "Visual Basic", Tactics: []string{"execution"}},
	"T1059.006": {Name: "Python", Tactics: []string{"execution"}},
	"T1059.007": {Name: "JavaScript", Tactics: []string{"execution"}},
	"T1059.008": {Name: "Network Device CLI", Tactics: []string{"execution"}},
	"T1059.009": {Name: "Cloud API", Tactics: []string{"execution"}},
	"T1059.010": {Name: "AutoHotKey & AutoIT", Tactics: []string{"execution"}},
	"T1059.011": {Name: "Lua", Tactics: []string{"execution"}},
	"T1059.012": {Name: "Hypervisor CLI", Tactics: []string{"execution"}},
	"T1059.013": {Name: "Container CLI/API", Tactics: []string{"execution"}},
	"T1060":     {Name: "Registry Run Keys / Startup Folder", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.001"},
	"T1061":     {Name: "Graphical User Interface", Tactics: []string{"execution"}, Deprecated: true},
	"T1062":     {Name: "Hypervisor", Tactics: []string{"persistence"}, Deprecated: true},
	"T1063":     {Name: "Security Software Discovery", Tactics: []string{"discovery"}, Revoked: true, Replacement: "T1518.001"},
	"T1064":     {Name: "Scripting", Tactics: []string{"execution", "stealth"}, Deprecated: true},
	"T1065":     {Name: "Uncommonly Used Port", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1571"},
	"T1066":     {Name: "Indicator Removal from Tools", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1027.005"},
	"T1067":     {Name: "Bootkit", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1542.003"},
	"T1068":     {Name: "Exploitation for Privilege Escalation", Tactics: []string{"privilege-escalation"}},
	"T1069":     {Name: "Permission Groups Discovery", Tactics: []string{"discovery"}},
	"T1069.001": {Name: "Local Groups", Tactics: []string{"discovery"}},
	"T1069.002": {Name: "Domain Groups", Tactics: []string{"discovery"}},
	"T1069.003": {Name: "Cloud Groups", Tactics: []string{"discovery"}},
	"T1070":     {Name: "Indicator Removal", Tactics: []string{"stealth"}},
	"T1070.001": {Name: "Clear Windows Event Logs", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685.005"},
	"T1070.002": {Name: "Clear Linux or Mac System Logs", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685.006"},
	"T1070.003": {Name: "Clear Command History", Tactics: []string{"stealth"}},
	"T1070.004": {Name: "File Deletion", Tactics: []string{"stealth"}},
	"T1070.005": {Name: "Network Share Connection Removal", Tactics: []string{"stealth"}},
	"T1070.006": {Name: "Timestomp", Tactics: []string{"stealth"}},
	"T1070.007": {Name: "Clear Network Connection History and Configurations", Tactics: []string{"stealth"}},
	"T1070.008": {Name: "Clear Mailbox Data", Tactics: []string{"stealth"}},
	"T1070.009": {Name: "Clear Persistence", Tactics: []string{"stealth"}},
	"T1070.010": {Name: "Relocate Malware", Tactics: []string{"stealth"}},
	"T1071":     {Name: "Application Layer Protocol", Tactics: []string{"command-and-control"}},
	"T1071.001": {Name: "Web Protocols", Tactics: []string{"command-and-control"}},
	"T1071.002": {Name: "File Transfer Protocols", Tactics: []string{"command-and-control"}},
	"T1071.003": {Name: "Mail Protocols", Tactics: []string{"command-and-control"}},
	"T1071.004": {Name: "DNS", Tactics: []string{"command-and-control"}},
	"T1071.005": {Name: "Publish/Subscribe Protocols", Tactics: []string{"command-and-control"}},
	"T1072":     {Name: "Software Deployment Tools", Tactics: []string{"execution", "lateral-movement"}},
	"T1073":     {Name: "DLL Side-Loading", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1574.002"},
	"T1074":     {Name: "Data Staged", Tactics: []string{"collection"}},
	"T1074.001": {Name: "Local Data Staging", Tactics: []string{"collection"}},
	"T1074.002": {Name: "Remote Data Staging", Tactics: []string{"collection"}},
	"T1075":     {Name: "Pass the Hash", Tactics: []string{"lateral-movement"}, Revoked: true, Replacement: "T1550.002"},
	"T1076":     {Name: "Remote Desktop Protocol", Tactics: []string{"lateral-movement"}, Revoked: true, Replacement: "T1021.001"},
	"T1077":     {Name: "Windows Admin Shares", Tactics: []string{"lateral-movement"}, Revoked: true, Replacement: "T1021.002"},
	"T1078":     {Name: "Valid Accounts", Tactics: []string{"initial-access", "persistence", "privilege-escalation", "stealth"}},
	"T1078.001": {Name: "Default Accounts", Tactics: []string{"initial-access", "persistence", "privilege-escalation", "stealth"}},
	"T1078.002": {Name: "Domain Accounts", Tactics: []string{"initial-access", "persistence", "privilege-escalation", "stealth"}},
	"T1078.003": {Name: "Local Accounts", Tactics: []string{"initial-access", "persistence", "privilege-escalation", "stealth"}},
	"T1078.004": {Name: "Cloud Accounts", Tactics: []string{"initial-access", "persistence", "privilege-escalation", "stealth"}},
	"T1079":     {Name: "Multilayer Encryption", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1573"},
	"T1080":     {Name: "Taint Shared Content", Tactics: []string{"lateral-movement"}},
	"T1081":     {Name: "Credentials in Files", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1552.001"},
	"T1082":     {Name: "System Information Discovery", Tactics: []string{"discovery"}},
	"T1083":     {Name: "File and Directory Discovery", Tactics: []string{"discovery"}},
	"T1084":     {Name: "Windows Management Instrumentation Event Subscription", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1546.003"},
	"T1085":     {Name: "Rundll32", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.011"},
	"T1086":     {Name: "PowerShell", Tactics: []string{"execution"}, Revoked: true, Replacement: "T1059.001"},
	"T1087":     {Name: "Account Discovery", Tactics: []string{"discovery"}},
	"T1087.001": {Name: "Local Account", Tactics: []string{"discovery"}},
	"T1087.002": {Name: "Domain Account", Tactics: []string{"discovery"}},
	"T1087.003": {Name: "Email Account", Tactics: []string{"discovery"}},
	"T1087.004": {Name: "Cloud Account", Tactics: []string{"discovery"}},
	"T1088":     {Name: "Bypass User Account Control", Tactics: []string{"privilege-escalation", "stealth"}, Revoked: true, Replacement: "T1548.002"},
	"T1089":     {Name: "Disabling Security Tools", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685"},
	"T1090":     {Name: "Proxy", Tactics: []string{"command-and-control"}},
	"T1090.001": {Name: "Internal Proxy", Tactics: []string{"command-and-control"}},
	"T1090.002": {Name: "External Proxy", Tactics: []string{"command-and-control"}},
	"T1090.003": {Name: "Multi-hop Proxy", Tactics: []string{"command-and-control"}},
	"T1090.004": {Name: "Domain Fronting", Tactics: []string{"command-and-control"}},
	"T1091":     {Name: "Replication Through Removable Media", Tactics: []string{"initial-access", "lateral-movement"}},
	"T1092":     {Name: "Communication Through Removable Media", Tactics: []string{"command-and-control"}},
	"T1093":     {Name: "Process Hollowing", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1055.012"},
	"T1094":     {Name: "Custom Command and Control Protocol", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1095"},
	"T1095":     {Name: "Non-Application Layer Protocol", Tactics: []string{"command-and-control"}},
	"T1096":     {Name: "NTFS File Attributes", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1564.004"},
	"T1097":     {Name: "Pass the Ticket", Tactics: []string{"lateral-movement"}, Revoked: true, Replacement: "T1550.003"},
	"T1098":     {Name: "Account Manipulation", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1098.001": {Name: "Additional Cloud Credentials", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1098.002": {Name: "Additional Email Delegate Permissions", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1098.003": {Name: "Additional Cloud Roles", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1098.004": {Name: "SSH Authorized Keys", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1098.005": {Name: "Device Registration", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1098.006": {Name: "Additional Container Cluster Roles", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1098.007": {Name: "Additional Local or Domain Groups", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1099":     {Name: "Timestomp", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1070.006"},
	"T1100":     {Name: "Web Shell", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1505.003"},
	"T1101":     {Name: "Security Support Provider", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.005"},
	"T1102":     {Name: "Web Service", Tactics: []string{"command-and-control"}},
	"T1102.001": {Name: "Dead Drop Resolver", Tactics: []string{"command-and-control"}},
	"T1102.002": {Name: "Bidirectional Communication", Tactics: []string{"command-and-control"}},
	"T1102.003": {Name: "One-Way Communication", Tactics: []string{"command-and-control"}},
	"T1103":     {Name: "AppInit DLLs", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1546.010"},
	"T1104":     {Name: "Multi-Stage Channels", Tactics: []string{"command-and-control"}},
	"T1105":     {Name: "Ingress Tool Transfer", Tactics: []string{"command-and-control"}},
	"T1106":     {Name: "Native API", Tactics: []string{"execution"}},
	"T1107":     {Name: "File Deletion", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1070.004"},
	"T1108":     {Name: "Redundant Access", Tactics: []string{"persistence", "stealth"}, Deprecated: true},
	"T1109":     {Name: "Component Firmware", Tactics: []string{"persistence", "stealth"}, Revoked: true, Replacement: "T1542.002"},
	"T1110":     {Name: "Brute Force", Tactics: []string{"credential-access"}},
	"T1110.001": {Name: "Password Guessing", Tactics: []string{"credential-access"}},
	"T1110.002": {Name: "Password Cracking", Tactics: []string{"credential-access"}},
	"T1110.003": {Name: "Password Spraying", Tactics: []string{"credential-access"}},
	"T1110.004": {Name: "Credential Stuffing", Tactics: []string{"credential-access"}},
	"T1111":     {Name: "Multi-Factor Authentication Interception", Tactics: []string{"credential-access"}},
	"T1112":     {Name: "Modify Registry", Tactics: []string{"defense-impairment", "persistence"}},
	"T1113":     {Name: "Screen Capture", Tactics: []string{"collection"}},
	"T1114":     {Name: "Email Collection", Tactics: []string{"collection"}},
	"T1114.001": {Name: "Local Email Collection", Tactics: []string{"collection"}},
	"T1114.002": {Name: "Remote Email Collection", Tactics: []string{"collection"}},
	"T1114.003": {Name: "Email Forwarding Rule", Tactics: []string{"collection"}},
	"T1115":     {Name: "Clipboard Data", Tactics: []string{"collection"}},
	"T1116":     {Name: "Code Signing", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1553.002"},
	"T1117":     {Name: "Regsvr32", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.010"},
	"T1118":     {Name: "InstallUtil", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.004"},
	"T1119":     {Name: "Automated Collection", Tactics: []string{"collection"}},
	"T1120":     {Name: "Peripheral Device Discovery", Tactics: []string{"discovery"}},
	"T1121":     {Name: "Regsvcs/Regasm", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.009"},
	"T1122":     {Name: "Component Object Model Hijacking", Tactics: []string{"persistence", "stealth"}, Revoked: true, Replacement: "T1546.015"},
	"T1123":     {Name: "Audio Capture", Tactics: []string{"collection"}},
	"T1124":     {Name: "System Time Discovery", Tactics: []string{"discovery"}},
	"T1125":     {Name: "Video Capture", Tactics: []string{"collection"}},
	"T1126":     {Name: "Network Share Connection Removal", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1070.005"},
	"T1127":     {Name: "Trusted Developer Utilities Proxy Execution", Tactics: []string{"execution", "stealth"}},
	"T1127.001": {Name: "MSBuild", Tactics: []string{"execution", "stealth"}},
	"T1127.002": {Name: "ClickOnce", Tactics: []string{"execution", "stealth"}},
	"T1127.003": {Name: "JamPlus", Tactics: []string{"execution", "stealth"}},
	"T1128":     {Name: "Netsh Helper DLL", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1546.007"},
	"T1129":     {Name: "Shared Modules", Tactics: []string{"execution"}},
	"T1130":     {Name: "Install Root Certificate", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1553.004"},
	"T1131":     {Name: "Authentication Package", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.002"},
	"T1132":     {Name: "Data Encoding", Tactics: []string{"command-and-control"}},
	"T1132.001": {Name: "Standard Encoding", Tactics: []string{"command-and-control"}},
	"T1132.002": {Name: "Non-Standard Encoding", Tactics: []string{"command-and-control"}},
	"T1133":     {Name: "External Remote Services", Tactics: []string{"initial-access", "persistence"}},
	"T1134":     {Name: "Access Token Manipulation", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1134.001": {Name: "Token Impersonation/Theft", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1134.002": {Name: "Create Process with Token", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1134.003": {Name: "Make and Impersonate Token", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1134.004": {Name: "Parent PID Spoofing", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1134.005": {Name: "SID-History Injection", Tactics: []string{"privilege-escalation", "stealth"}},
	"T1135":     {Name: "Network Share Discovery", Tactics: []string{"discovery"}},
	"T1136":     {Name: "Create Account", Tactics: []string{"persistence"}},
	"T1136.001": {Name: "Local Account", Tactics: []string{"persistence"}},
	"T1136.002": {Name: "Domain Account", Tactics: []string{"persistence"}},
	"T1136.003": {Name: "Cloud Account", Tactics: []string{"persistence"}},
	"T1137":     {Name: "Office Application Startup", Tactics: []string{"persistence"}},
	"T1137.001": {Name: "Office Template Macros", Tactics: []string{"persistence"}},
	"T1137.002": {Name: "Office Test", Tactics: []string{"persistence"}},
	"T1137.003": {Name: "Outlook Forms", Tactics: []string{"persistence"}},
	"T1137.004": {Name: "Outlook Home Page", Tactics: []string{"persistence"}},
	"T1137.005": {Name: "Outlook Rules", Tactics: []string{"persistence"}},
	"T1137.006": {Name: "Add-ins", Tactics: []string{"persistence"}},
	"T1138":     {Name: "Application Shimming", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1546.011"},
	"T1139":     {Name: "Bash History", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1552.003"},
	"T1140":     {Name: "Deobfuscate/Decode Files or Information", Tactics: []string{"stealth"}},
	"T1141":     {Name: "Input Prompt", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1056.002"},
	"T1142":     {Name: "Keychain", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1555.001"},
	"T1143":     {Name: "Hidden Window", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1564.003"},
	"T1144":     {Name: "Gatekeeper Bypass", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1553.001"},
	"T1145":     {Name: "Private Keys", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1552.004"},
	"T1146":     {Name: "Clear Command History", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1070.003"},
	"T1147":     {Name: "Hidden Users", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1564.002"},
	"T1148":     {Name: "HISTCONTROL", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1690"},
	"T1149":     {Name: "LC_MAIN Hijacking", Tactics: []string{"stealth"}, Deprecated: true},
	"T1150":     {Name: "Plist Modification", Tactics: []string{"persistence", "privilege-escalation", "stealth"}, Revoked: true, Replacement: "T1547.011"},
	"T1151":     {Name: "Space after Filename", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1036.006"},
	"T1152":     {Name: "Launchctl", Tactics: []string{"execution", "persistence", "stealth"}, Revoked: true, Replacement: "T1569.001"},
	"T1153":     {Name: "Source", Tactics: []string{"execution"}, Deprecated: true},
	"T1154":     {Name: "Trap", Tactics: []string{"execution", "persistence"}, Revoked: true, Replacement: "T1546.005"},
	"T1155":     {Name: "AppleScript", Tactics: []string{"execution"}, Revoked: true, Replacement: "T1059.002"},
	"T1156":     {Name: "Malicious Shell Modification", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1546.004"},
	"T1157":     {Name: "Dylib Hijacking", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1574.004"},
	"T1158":     {Name: "Hidden Files and Directories", Tactics: []string{"persistence", "stealth"}, Revoked: true, Replacement: "T1564.001"},
	"T1159":     {Name: "Launch Agent", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1543.001"},
	"T1160":     {Name: "Launch Daemon", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1543.004"},
	"T1161":     {Name: "LC_LOAD_DYLIB Addition", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1546.006"},
	"T1162":     {Name: "Login Item", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.011"},
	"T1163":     {Name: "Rc.common", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1037.004"},
	"T1164":     {Name: "Re-opened Applications", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.007"},
	"T1165":     {Name: "Startup Items", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1037.005"},
	"T1166":     {Name: "Setuid and Setgid", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1548.001"},
	"T1167":     {Name: "Securityd Memory", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1555.002"},
	"T1168":     {Name: "Local Job Scheduling", Tactics: []string{"execution", "persistence"}, Revoked: true, Replacement: "T1053"},
	"T1169":     {Name: "Sudo", Tactics: []string{"privilege-escalation"}, Revoked: true, Replacement: "T1548.003"},
	"T1170":     {Name: "Mshta", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.005"},
	"T1171":     {Name: "LLMNR/NBT-NS Poisoning and Relay", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1557.001"},
	"T1172":     {Name: "Domain Fronting", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1090.004"},
	"T1173":     {Name: "Dynamic Data Exchange", Tactics: []string{"execution"}, Revoked: true, Replacement: "T1559.002"},
	"T1174":     {Name: "Password Filter DLL", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1556.002"},
	"T1175":     {Name: "Component Object Model and Distributed COM", Tactics: []string{"execution", "lateral-movement"}, Deprecated: true},
	"T1176":     {Name: "Software Extensions", Tactics: []string{"persistence"}},
	"T1176.001": {Name: "Browser Extensions", Tactics: []string{"persistence"}},
	"T1176.002": {Name: "IDE Extensions", Tactics: []string{"persistence"}},
	"T1177":     {Name: "LSASS Driver", Tactics: []string{"execution", "persistence"}, Revoked: true, Replacement: "T1547.008"},
	"T1178":     {Name: "SID-History Injection", Tactics: []string{"privilege-escalation"}, Revoked: true, Replacement: "T1134.005"},
	"T1179":     {Name: "Hooking", Tactics: []string{"credential-access", "persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1056.004"},
	"T1180":     {Name: "Screensaver", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1546.002"},
	"T1181":     {Name: "Extra Window Memory Injection", Tactics: []string{"privilege-escalation", "stealth"}, Revoked: true, Replacement: "T1055.011"},
	"T1182":     {Name: "AppCert DLLs", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1546.009"},
	"T1183":     {Name: "Image File Execution Options Injection", Tactics: []string{"persistence", "privilege-escalation", "stealth"}, Revoked: true, Replacement: "T1546.012"},
	"T1184":     {Name: "SSH Hijacking", Tactics: []string{"lateral-movement"}, Revoked: true, Replacement: "T1563.001"},
	"T1185":     {Name: "Browser Session Hijacking", Tactics: []string{"collection"}},
	"T1186":     {Name: "Process Doppelgänging", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1055.013"},
	"T1187":     {Name: "Forced Authentication", Tactics: []string{"credential-access"}},
	"T1188":     {Name: "Multi-hop Proxy", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1090.003"},
	"T1189":     {Name: "Drive-by Compromise", Tactics: []string{"initial-access"}},
	"T1190":     {Name: "Exploit Public-Facing Application", Tactics: []string{"initial-access"}},
	"T1191":     {Name: "CMSTP", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.003"},
	"T1192":     {Name: "Spearphishing Link", Tactics: []string{"initial-access"}, Revoked: true, Replacement: "T1566.002"},
	"T1193":     {Name: "Spearphishing Attachment", Tactics: []string{"initial-access"}, Revoked: true, Replacement: "T1566.001"},
	"T1194":     {Name: "Spearphishing via Service", Tactics: []string{"initial-access"}, Revoked: true, Replacement: "T1566.003"},
	"T1195":     {Name: "Supply Chain Compromise", Tactics: []string{"initial-access"}},
	"T1195.001": {Name: "Compromise Software Dependencies and Development Tools", Tactics: []string{"initial-access"}},
	"T1195.002": {Name: "Compromise Software Supply Chain", Tactics: []string{"initial-access"}},
	"T1195.003": {Name: "Compromise Hardware Supply Chain", Tactics: []string{"initial-access"}},
	"T1196":     {Name: "Control Panel Items", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.002"},
	"T1197":     {Name: "BITS Jobs", Tactics: []string{"execution", "persistence", "stealth"}},
	"T1198":     {Name: "SIP and Trust Provider Hijacking", Tactics: []string{"persistence", "stealth"}, Revoked: true, Replacement: "T1553.003"},
	"T1199":     {Name: "Trusted Relationship", Tactics: []string{"initial-access"}},
	"T1200":     {Name: "Hardware Additions", Tactics: []string{"initial-access"}},
	"T1201":     {Name: "Password Policy Discovery", Tactics: []string{"discovery"}},
	"T1202":     {Name: "Indirect Command Execution", Tactics: []string{"stealth"}},
	"T1203":     {Name: "Exploitation for Client Execution", Tactics: []string{"execution"}},
	"T1204":     {Name: "User Execution", Tactics: []string{"execution"}},
	"T1204.001": {Name: "Malicious Link", Tactics: []string{"execution"}},
	"T1204.002": {Name: "Malicious File", Tactics: []string{"execution"}},
	"T1204.003": {Name: "Malicious Image", Tactics: []string{"execution"}},
	"T1204.004": {Name: "Malicious Copy and Paste", Tactics: []string{"execution"}},
	"T1204.005": {Name: "Malicious Library", Tactics: []string{"execution"}},
	"T1205":     {Name: "Traffic Signaling", Tactics: []string{"command-and-control", "persistence", "stealth"}},
	"T1205.001": {Name: "Port Knocking", Tactics: []string{"command-and-control", "persistence", "stealth"}},
	"T1205.002": {Name: "Socket Filters", Tactics: []string{"command-and-control", "persistence", "stealth"}},
	"T1206":     {Name: "Sudo Caching", Tactics: []string{"privilege-escalation"}, Revoked: true, Replacement: "T1548.003"},
	"T1207":     {Name: "Rogue Domain Controller", Tactics: []string{"defense-impairment"}},
	"T1208":     {Name: "Kerberoasting", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1558.003"},
	"T1209":     {Name: "Time Providers", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.003"},
	"T1210":     {Name: "Exploitation of Remote Services", Tactics: []string{"lateral-movement"}},
	"T1211":     {Name: "Exploitation for Stealth", Tactics: []string{"stealth"}},
	"T1212":     {Name: "Exploitation for Credential Access", Tactics: []string{"credential-access"}},
	"T1213":     {Name: "Data from Information Repositories", Tactics: []string{"collection"}},
	"T1213.001": {Name: "Confluence", Tactics: []string{"collection"}},
	"T1213.002": {Name: "Sharepoint", Tactics: []string{"collection"}},
	"T1213.003": {Name: "Code Repositories", Tactics: []string{"collection"}},
	"T1213.004": {Name: "Customer Relationship Management Software", Tactics: []string{"collection"}},
	"T1213.005": {Name: "Messaging Applications", Tactics: []string{"collection"}},
	"T1213.006": {Name: "Databases", Tactics: []string{"collection"}},
	"T1214":     {Name: "Credentials in Registry", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1552.002"},
	"T1215":     {Name: "Kernel Modules and Extensions", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1547.006"},
	"T1216":     {Name: "System Script Proxy Execution", Tactics: []string{"stealth"}},
	"T1216.001": {Name: "PubPrn", Tactics: []string{"stealth"}},
	"T1216.002": {Name: "SyncAppvPublishingServer", Tactics: []string{"stealth"}},
	"T1217":     {Name: "Browser Information Discovery", Tactics: []string{"discovery"}},
	"T1218":     {Name: "System Binary Proxy Execution", Tactics: []string{"stealth"}},
	"T1218.001": {Name: "Compiled HTML File", Tactics: []string{"stealth"}},
	"T1218.002": {Name: "Control Panel", Tactics: []string{"stealth"}},
	"T1218.003": {Name: "CMSTP", Tactics: []string{"stealth"}},
	"T1218.004": {Name: "InstallUtil", Tactics: []string{"stealth"}},
	"T1218.005": {Name: "Mshta", Tactics: []string{"stealth"}},
	"T1218.007": {Name: "Msiexec", Tactics: []string{"stealth"}},
	"T1218.008": {Name: "Odbcconf", Tactics: []string{"stealth"}},
	"T1218.009": {Name: "Regsvcs/Regasm", Tactics: []string{"stealth"}},
	"T1218.010": {Name: "Regsvr32", Tactics: []string{"stealth"}},
	"T1218.011": {Name: "Rundll32", Tactics: []string{"stealth"}},
	"T1218.012": {Name: "Verclsid", Tactics: []string{"stealth"}},
	"T1218.013": {Name: "Mavinject", Tactics: []string{"stealth"}},
	"T1218.014": {Name: "MMC", Tactics: []string{"stealth"}},
	"T1218.015": {Name: "Electron Applications", Tactics: []string{"stealth"}},
	"T1219":     {Name: "Remote Access Tools", Tactics: []string{"command-and-control"}},
	"T1219.001": {Name: "IDE Tunneling", Tactics: []string{"command-and-control"}},
	"T1219.002": {Name: "Remote Desktop Software", Tactics: []string{"command-and-control"}},
	"T1219.003": {Name: "Remote Access Hardware", Tactics: []string{"command-and-control"}},
	"T1220":     {Name: "XSL Script Processing", Tactics: []string{"stealth"}},
	"T1221":     {Name: "Template Injection", Tactics: []string{"stealth"}},
	"T1222":     {Name: "File and Directory Permissions Modification", Tactics: []string{"defense-impairment"}},
	"T1222.001": {Name: "Windows Permissions", Tactics: []string{"defense-impairment"}},
	"T1222.002": {Name: "Linux and Mac Permissions", Tactics: []string{"defense-impairment"}},
	"T1223":     {Name: "Compiled HTML File", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1218.001"},
	"T1480":     {Name: "Execution Guardrails", Tactics: []string{"stealth"}},
	"T1480.001": {Name: "Environmental Keying", Tactics: []string{"stealth"}},
	"T1480.002": {Name: "Mutual Exclusion", Tactics: []string{"stealth"}},
	"T1482":     {Name: "Domain Trust Discovery", Tactics: []string{"discovery"}},
	"T1483":     {Name: "Domain Generation Algorithms", Tactics: []string{"command-and-control"}, Revoked: true, Replacement: "T1568.002"},
	"T1484":     {Name: "Domain or Tenant Policy Modification", Tactics: []string{"defense-impairment", "privilege-escalation"}},
	"T1484.001": {Name: "Group Policy Modification", Tactics: []string{"defense-impairment", "privilege-escalation"}},
	"T1484.002": {Name: "Trust Modification", Tactics: []string{"defense-impairment", "privilege-escalation"}},
	"T1485":     {Name: "Data Destruction", Tactics: []string{"impact"}},
	"T1485.001": {Name: "Lifecycle-Triggered Deletion", Tactics: []string{"impact"}},
	"T1486":     {Name: "Data Encrypted for Impact", Tactics: []string{"impact"}},
	"T1487":     {Name: "Disk Structure Wipe", Tactics: []string{"impact"}, Revoked: true, Replacement: "T1561.002"},
	"T1488":     {Name: "Disk Content Wipe", Tactics: []string{"impact"}, Revoked: true, Replacement: "T1561.001"},
	"T1489":     {Name: "Service Stop", Tactics: []string{"impact"}},
	"T1490":     {Name: "Inhibit System Recovery", Tactics: []string{"impact"}},
	"T1491":     {Name: "Defacement", Tactics: []string{"impact"}},
	"T1491.001": {Name: "Internal Defacement", Tactics: []string{"impact"}},
	"T1491.002": {Name: "External Defacement", Tactics: []string{"impact"}},
	"T1492":     {Name: "Stored Data Manipulation", Tactics: []string{"impact"}, Revoked: true, Replacement: "T1565.001"},
	"T1493":     {Name: "Transmitted Data Manipulation", Tactics: []string{"impact"}, Revoked: true, Replacement: "T1565.002"},
	"T1494":     {Name: "Runtime Data Manipulation", Tactics: []string{"impact"}, Revoked: true, Replacement: "T1565.003"},
	"T1495":     {Name: "Firmware Corruption", Tactics: []string{"impact"}},
	"T1496":     {Name: "Resource Hijacking", Tactics: []string{"impact"}},
	"T1496.001": {Name: "Compute Hijacking", Tactics: []string{"impact"}},
	"T1496.002": {Name: "Bandwidth Hijacking", Tactics: []string{"impact"}},
	"T1496.003": {Name: "SMS Pumping", Tactics: []string{"impact"}},
	"T1496.004": {Name: "Cloud Service Hijacking", Tactics: []string{"impact"}},
	"T1497":     {Name: "Virtualization/Sandbox Evasion", Tactics: []string{"discovery", "stealth"}},
	"T1497.001": {Name: "System Checks", Tactics: []string{"discovery", "stealth"}},
	"T1497.002": {Name: "User Activity Based Checks", Tactics: []string{"discovery", "stealth"}},
	"T1497.003": {Name: "Time Based Checks", Tactics: []string{"discovery", "stealth"}},
	"T1498":     {Name: "Network Denial of Service", Tactics: []string{"impact"}},
	"T1498.001": {Name: "Direct Network Flood", Tactics: []string{"impact"}},
	"T1498.002": {Name: "Reflection Amplification", Tactics: []string{"impact"}},
	"T1499":     {Name: "Endpoint Denial of Service", Tactics: []string{"impact"}},
	"T1499.001": {Name: "OS Exhaustion Flood", Tactics: []string{"impact"}},
	"T1499.002": {Name: "Service Exhaustion Flood", Tactics: []string{"impact"}},
	"T1499.003": {Name: "Application Exhaustion Flood", Tactics: []string{"impact"}},
	"T1499.004": {Name: "Application or System Exploitation", Tactics: []string{"impact"}},
	"T1500":     {Name: "Compile After Delivery", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1027.004"},
	"T1501":     {Name: "Systemd Service", Tactics: []string{"persistence"}, Revoked: true, Replacement: "T1543.002"},
	"T1502":     {Name: "Parent PID Spoofing", Tactics: []string{"privilege-escalation", "stealth"}, Revoked: true, Replacement: "T1134.004"},
	"T1503":     {Name: "Credentials from Web Browsers", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1555.003"},
	"T1504":     {Name: "PowerShell Profile", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1546.013"},
	"T1505":     {Name: "Server Software Component", Tactics: []string{"persistence"}},
	"T1505.001": {Name: "SQL Stored Procedures", Tactics: []string{"persistence"}},
	"T1505.002": {Name: "Transport Agent", Tactics: []string{"persistence"}},
	"T1505.003": {Name: "Web Shell", Tactics: []string{"persistence"}},
	"T1505.004": {Name: "IIS Components", Tactics: []string{"persistence"}},
	"T1505.005": {Name: "Terminal Services DLL", Tactics: []string{"persistence"}},
	"T1505.006": {Name: "vSphere Installation Bundles", Tactics: []string{"persistence"}},
	"T1506":     {Name: "Web Session Cookie", Tactics: []string{"lateral-movement", "stealth"}, Revoked: true, Replacement: "T1550.004"},
	"T1514":     {Name: "Elevated Execution with Prompt", Tactics: []string{"privilege-escalation"}, Revoked: true, Replacement: "T1548.004"},
	"T1518":     {Name: "Software Discovery", Tactics: []string{"discovery"}},
	"T1518.001": {Name: "Security Software Discovery", Tactics: []string{"discovery"}},
	"T1518.002": {Name: "Backup Software Discovery", Tactics: []string{"discovery"}},
	"T1519":     {Name: "Emond", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1546.014"},
	"T1522":     {Name: "Cloud Instance Metadata API", Tactics: []string{"credential-access"}, Revoked: true, Replacement: "T1552.005"},
	"T1525":     {Name: "Implant Internal Image", Tactics: []string{"persistence"}},
	"T1526":     {Name: "Cloud Service Discovery", Tactics: []string{"discovery"}},
	"T1527":     {Name: "Application Access Token", Tactics: []string{"lateral-movement", "stealth"}, Revoked: true, Replacement: "T1550.001"},
	"T1528":     {Name: "Steal Application Access Token", Tactics: []string{"credential-access"}},
	"T1529":     {Name: "System Shutdown/Reboot", Tactics: []string{"impact"}},
	"T1530":     {Name: "Data from Cloud Storage", Tactics: []string{"collection"}},
	"T1531":     {Name: "Account Access Removal", Tactics: []string{"impact"}},
	"T1534":     {Name: "Internal Spearphishing", Tactics: []string{"lateral-movement"}},
	"T1535":     {Name: "Unused/Unsupported Cloud Regions", Tactics: []string{"stealth"}},
	"T1536":     {Name: "Revert Cloud Instance", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1578.004"},
	"T1537":     {Name: "Transfer Data to Cloud Account", Tactics: []string{"exfiltration"}},
	"T1538":     {Name: "Cloud Service Dashboard", Tactics: []string{"discovery"}},
	"T1539":     {Name: "Steal Web Session Cookie", Tactics: []string{"credential-access"}},
	"T1542":     {Name: "Pre-OS Boot", Tactics: []string{"persistence", "stealth"}},
	"T1542.001": {Name: "System Firmware", Tactics: []string{"persistence", "stealth"}},
	"T1542.002": {Name: "Component Firmware", Tactics: []string{"persistence", "stealth"}},
	"T1542.003": {Name: "Bootkit", Tactics: []string{"persistence", "stealth"}},
	"T1542.004": {Name: "ROMMONkit", Tactics: []string{"persistence", "stealth"}},
	"T1542.005": {Name: "TFTP Boot", Tactics: []string{"persistence", "stealth"}},
	"T1543":     {Name: "Create or Modify System Process", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1543.001": {Name: "Launch Agent", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1543.002": {Name: "Systemd Service", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1543.003": {Name: "Windows Service", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1543.004": {Name: "Launch Daemon", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1543.005": {Name: "Container Service", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546":     {Name: "Event Triggered Execution", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.001": {Name: "Change Default File Association", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.002": {Name: "Screensaver", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.003": {Name: "Windows Management Instrumentation Event Subscription", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.004": {Name: "Unix Shell Configuration Modification", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.005": {Name: "Trap", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.006": {Name: "LC_LOAD_DYLIB Addition", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.007": {Name: "Netsh Helper DLL", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.008": {Name: "Accessibility Features", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.009": {Name: "AppCert DLLs", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.010": {Name: "AppInit DLLs", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.011": {Name: "Application Shimming", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.012": {Name: "Image File Execution Options Injection", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.013": {Name: "PowerShell Profile", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.014": {Name: "Emond", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.015": {Name: "Component Object Model Hijacking", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.016": {Name: "Installer Packages", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.017": {Name: "Udev Rules", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1546.018": {Name: "Python Startup Hooks", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547":     {Name: "Boot or Logon Autostart Execution", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.001": {Name: "Registry Run Keys / Startup Folder", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.002": {Name: "Authentication Package", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.003": {Name: "Time Providers", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.004": {Name: "Winlogon Helper DLL", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.005": {Name: "Security Support Provider", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.006": {Name: "Kernel Modules and Extensions", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.007": {Name: "Re-opened Applications", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.008": {Name: "LSASS Driver", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.009": {Name: "Shortcut Modification", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.010": {Name: "Port Monitors", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.011": {Name: "Plist Modification", Tactics: []string{"persistence", "privilege-escalation"}, Revoked: true, Replacement: "T1647"},
	"T1547.012": {Name: "Print Processors", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.013": {Name: "XDG Autostart Entries", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.014": {Name: "Active Setup", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1547.015": {Name: "Login Items", Tactics: []string{"persistence", "privilege-escalation"}},
	"T1548":     {Name: "Abuse Elevation Control Mechanism", Tactics: []string{"privilege-escalation"}},
	"T1548.001": {Name: "Setuid and Setgid", Tactics: []string{"privilege-escalation"}},
	"T1548.002": {Name: "Bypass User Account Control", Tactics: []string{"privilege-escalation"}},
	"T1548.003": {Name: "Sudo and Sudo Caching", Tactics: []string{"privilege-escalation"}},
	"T1548.004": {Name: "Elevated Execution with Prompt", Tactics: []string{"privilege-escalation"}},
	"T1548.005": {Name: "Temporary Elevated Cloud Access", Tactics: []string{"privilege-escalation"}},
	"T1548.006": {Name: "TCC Manipulation", Tactics: []string{"privilege-escalation"}},
	"T1550":     {Name: "Use Alternate Authentication Material", Tactics: []string{"lateral-movement"}},
	"T1550.001": {Name: "Application Access Token", Tactics: []string{"lateral-movement"}},
	"T1550.002": {Name: "Pass the Hash", Tactics: []string{"lateral-movement"}},
	"T1550.003": {Name: "Pass the Ticket", Tactics: []string{"lateral-movement"}},
	"T1550.004": {Name: "Web Session Cookie", Tactics: []string{"lateral-movement"}},
	"T1552":     {Name: "Unsecured Credentials", Tactics: []string{"credential-access"}},
	"T1552.001": {Name: "Credentials In Files", Tactics: []string{"credential-access"}},
	"T1552.002": {Name: "Credentials in Registry", Tactics: []string{"credential-access"}},
	"T1552.003": {Name: "Shell History", Tactics: []string{"credential-access"}},
	"T1552.004": {Name: "Private Keys", Tactics: []string{"credential-access"}},
	"T1552.005": {Name: "Cloud Instance Metadata API", Tactics: []string{"credential-access"}},
	"T1552.006": {Name: "Group Policy Preferences", Tactics: []string{"credential-access"}},
	"T1552.007": {Name: "Container API", Tactics: []string{"credential-access"}},
	"T1552.008": {Name: "Chat Messages", Tactics: []string{"credential-access"}},
	"T1553":     {Name: "Subvert Trust Controls", Tactics: []string{"defense-impairment"}},
	"T1553.001": {Name: "Gatekeeper Bypass", Tactics: []string{"defense-impairment"}},
	"T1553.002": {Name: "Code Signing", Tactics: []string{"defense-impairment"}},
	"T1553.003": {Name: "SIP and Trust Provider Hijacking", Tactics: []string{"defense-impairment"}},
	"T1553.004": {Name: "Install Root Certificate", Tactics: []string{"defense-impairment"}},
	"T1553.005": {Name: "Mark-of-the-Web Bypass", Tactics: []string{"defense-impairment"}},
	"T1553.006": {Name: "Code Signing Policy Modification", Tactics: []string{"defense-impairment"}},
	"T1554":     {Name: "Compromise Host Software Binary", Tactics: []string{"persistence"}},
	"T1555":     {Name: "Credentials from Password Stores", Tactics: []string{"credential-access"}},
	"T1555.001": {Name: "Keychain", Tactics: []string{"credential-access"}},
	"T1555.002": {Name: "Securityd Memory", Tactics: []string{"credential-access"}},
	"T1555.003": {Name: "Credentials from Web Browsers", Tactics: []string{"credential-access"}},
	"T1555.004": {Name: "Windows Credential Manager", Tactics: []string{"credential-access"}},
	"T1555.005": {Name: "Password Managers", Tactics: []string{"credential-access"}},
	"T1555.006": {Name: "Cloud Secrets Management Stores", Tactics: []string{"credential-access"}},
	"T1556":     {Name: "Modify Authentication Process", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.001": {Name: "Domain Controller Authentication", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.002": {Name: "Password Filter DLL", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.003": {Name: "Pluggable Authentication Modules", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.004": {Name: "Network Device Authentication", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.005": {Name: "Reversible Encryption", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.006": {Name: "Multi-Factor Authentication", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.007": {Name: "Hybrid Identity", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.008": {Name: "Network Provider DLL", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1556.009": {Name: "Conditional Access Policies", Tactics: []string{"credential-access", "defense-impairment", "persistence"}},
	"T1557":     {Name: "Adversary-in-the-Middle", Tactics: []string{"collection", "credential-access"}},
	"T1557.001": {Name: "Name Resolution Poisoning and SMB Relay", Tactics: []string{"collection", "credential-access"}},
	"T1557.002": {Name: "ARP Cache Poisoning", Tactics: []string{"collection", "credential-access"}},
	"T1557.003": {Name: "DHCP Spoofing", Tactics: []string{"collection", "credential-access"}},
	"T1557.004": {Name: "Evil Twin", Tactics: []string{"collection", "credential-access"}},
	"T1558":     {Name: "Steal or Forge Kerberos Tickets", Tactics: []string{"credential-access"}},
	"T1558.001": {Name: "Golden Ticket", Tactics: []string{"credential-access"}},
	"T1558.002": {Name: "Silver Ticket", Tactics: []string{"credential-access"}},
	"T1558.003": {Name: "Kerberoasting", Tactics: []string{"credential-access"}},
	"T1558.004": {Name: "AS-REP Roasting", Tactics: []string{"credential-access"}},
	"T1558.005": {Name: "Ccache Files", Tactics: []string{"credential-access"}},
	"T1559":     {Name: "Inter-Process Communication", Tactics: []string{"execution"}},
	"T1559.001": {Name: "Component Object Model", Tactics: []string{"execution"}},
	"T1559.002": {Name: "Dynamic Data Exchange", Tactics: []string{"execution"}},
	"T1559.003": {Name: "XPC Services", Tactics: []string{"execution"}},
	"T1560":     {Name: "Archive Collected Data", Tactics: []string{"collection"}},
	"T1560.001": {Name: "Archive via Utility", Tactics: []string{"collection"}},
	"T1560.002": {Name: "Archive via Library", Tactics: []string{"collection"}},
	"T1560.003": {Name: "Archive via Custom Method", Tactics: []string{"collection"}},
	"T1561":     {Name: "Disk Wipe", Tactics: []string{"impact"}},
	"T1561.001": {Name: "Disk Content Wipe", Tactics: []string{"impact"}},
	"T1561.002": {Name: "Disk Structure Wipe", Tactics: []string{"impact"}},
	"T1562":     {Name: "Impair Defenses", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685"},
	"T1562.001": {Name: "Disable or Modify Tools", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685"},
	"T1562.002": {Name: "Disable Windows Event Logging", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685.001"},
	"T1562.003": {Name: "Impair Command History Logging", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1690"},
	"T1562.004": {Name: "Disable or Modify System Firewall", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1686"},
	"T1562.006": {Name: "Indicator Blocking", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685"},
	"T1562.007": {Name: "Disable or Modify Cloud Firewall", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1686.001"},
	"T1562.008": {Name: "Disable or Modify Cloud Logs", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685.002"},
	"T1562.009": {Name: "Safe Mode Boot", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1688"},
	"T1562.010": {Name: "Downgrade Attack", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1689"},
	"T1562.011": {Name: "Spoof Security Alerting", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685.003"},
	"T1562.012": {Name: "Disable or Modify Linux Audit System", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1685.004"},
	"T1562.013": {Name: "Disable or Modify Network Device Firewall", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1686.002"},
	"T1563":     {Name: "Remote Service Session Hijacking", Tactics: []string{"lateral-movement"}},
	"T1563.001": {Name: "SSH Hijacking", Tactics: []string{"lateral-movement"}},
	"T1563.002": {Name: "RDP Hijacking", Tactics: []string{"lateral-movement"}},
	"T1564":     {Name: "Hide Artifacts", Tactics: []string{"stealth"}},
	"T1564.001": {Name: "Hidden Files and Directories", Tactics: []string{"stealth"}},
	"T1564.002": {Name: "Hidden Users", Tactics: []string{"stealth"}},
	"T1564.003": {Name: "Hidden Window", Tactics: []string{"stealth"}},
	"T1564.004": {Name: "NTFS File Attributes", Tactics: []string{"stealth"}},
	"T1564.005": {Name: "Hidden File System", Tactics: []string{"stealth"}},
	"T1564.006": {Name: "Run Virtual Instance", Tactics: []string{"stealth"}},
	"T1564.007": {Name: "VBA Stomping", Tactics: []string{"stealth"}},
	"T1564.008": {Name: "Email Hiding Rules", Tactics: []string{"stealth"}},
	"T1564.009": {Name: "Resource Forking", Tactics: []string{"stealth"}},
	"T1564.010": {Name: "Process Argument Spoofing", Tactics: []string{"stealth"}},
	"T1564.011": {Name: "Ignore Process Interrupts", Tactics: []string{"stealth"}},
	"T1564.012": {Name: "File/Path Exclusions", Tactics: []string{"stealth"}},
	"T1564.013": {Name: "Bind Mounts", Tactics: []string{"stealth"}},
	"T1564.014": {Name: "Extended Attributes", Tactics: []string{"stealth"}},
	"T1565":     {Name: "Data Manipulation", Tactics: []string{"impact"}},
	"T1565.001": {Name: "Stored Data Manipulation", Tactics: []string{"impact"}},
	"T1565.002": {Name: "Transmitted Data Manipulation", Tactics: []string{"impact"}},
	"T1565.003": {Name: "Runtime Data Manipulation", Tactics: []string{"impact"}},
	"T1566":     {Name: "Phishing", Tactics: []string{"initial-access"}},
	"T1566.001": {Name: "Spearphishing Attachment", Tactics: []string{"initial-access"}},
	"T1566.002": {Name: "Spearphishing Link", Tactics: []string{"initial-access"}},
	"T1566.003": {Name: "Spearphishing via Service", Tactics: []string{"initial-access"}},
	"T1566.004": {Name: "Spearphishing Voice", Tactics: []string{"initial-access"}},
	"T1567":     {Name: "Exfiltration Over Web Service", Tactics: []string{"exfiltration"}},
	"T1567.001": {Name: "Exfiltration to Code Repository", Tactics: []string{"exfiltration"}},
	"T1567.002": {Name: "Exfiltration to Cloud Storage", Tactics: []string{"exfiltration"}},
	"T1567.003": {Name: "Exfiltration to Text Storage Sites", Tactics: []string{"exfiltration"}},
	"T1567.004": {Name: "Exfiltration Over Webhook", Tactics: []string{"exfiltration"}},
	"T1568":     {Name: "Dynamic Resolution", Tactics: []string{"command-and-control"}},
	"T1568.001": {Name: "Fast Flux DNS", Tactics: []string{"command-and-control"}},
	"T1568.002": {Name: "Domain Generation Algorithms", Tactics: []string{"command-and-control"}},
	"T1568.003": {Name: "DNS Calculation", Tactics: []string{"command-and-control"}},
	"T1569":     {Name: "System Services", Tactics: []string{"execution"}},
	"T1569.001": {Name: "Launchctl", Tactics: []string{"execution"}},
	"T1569.002": {Name: "Service Execution", Tactics: []string{"execution"}},
	"T1569.003": {Name: "Systemctl", Tactics: []string{"execution"}},
	"T1570":     {Name: "Lateral Tool Transfer", Tactics: []string{"lateral-movement"}},
	"T1571":     {Name: "Non-Standard Port", Tactics: []string{"command-and-control"}},
	"T1572":     {Name: "Protocol Tunneling", Tactics: []string{"command-and-control"}},
	"T1573":     {Name: "Encrypted Channel", Tactics: []string{"command-and-control"}},
	"T1573.001": {Name: "Symmetric Cryptography", Tactics: []string{"command-and-control"}},
	"T1573.002": {Name: "Asymmetric Cryptography", Tactics: []string{"command-and-control"}},
	"T1574":     {Name: "Hijack Execution Flow", Tactics: []string{"execution", "stealth"}},
	"T1574.001": {Name: "DLL", Tactics: []string{"execution", "stealth"}},
	"T1574.002": {Name: "DLL Side-Loading", Tactics: []string{"execution", "stealth"}, Revoked: true, Replacement: "T1574.001"},
	"T1574.004": {Name: "Dylib Hijacking", Tactics: []string{"execution", "stealth"}},
	"T1574.005": {Name: "Executable Installer File Permissions Weakness", Tactics: []string{"execution", "stealth"}},
	"T1574.006": {Name: "Dynamic Linker Hijacking", Tactics: []string{"execution", "stealth"}},
	"T1574.007": {Name: "Path Interception by PATH Environment Variable", Tactics: []string{"execution", "stealth"}},
	"T1574.008": {Name: "Path Interception by Search Order Hijacking", Tactics: []string{"execution", "stealth"}},
	"T1574.009": {Name: "Path Interception by Unquoted Path", Tactics: []string{"execution", "stealth"}},
	"T1574.010": {Name: "Services File Permissions Weakness", Tactics: []string{"execution", "stealth"}},
	"T1574.011": {Name: "Services Registry Permissions Weakness", Tactics: []string{"execution", "stealth"}},
	"T1574.012": {Name: "COR_PROFILER", Tactics: []string{"execution", "stealth"}},
	"T1574.013": {Name: "KernelCallbackTable", Tactics: []string{"execution", "stealth"}},
	"T1574.014": {Name: "AppDomainManager", Tactics: []string{"execution", "stealth"}},
	"T1578":     {Name: "Modify Cloud Compute Infrastructure", Tactics: []string{"defense-impairment"}},
	"T1578.001": {Name: "Create Snapshot", Tactics: []string{"defense-impairment"}},
	"T1578.002": {Name: "Create Cloud Instance", Tactics: []string{"defense-impairment"}},
	"T1578.003": {Name: "Delete Cloud Instance", Tactics: []string{"defense-impairment"}},
	"T1578.004": {Name: "Revert Cloud Instance", Tactics: []string{"defense-impairment"}},
	"T1578.005": {Name: "Modify Cloud Compute Configurations", Tactics: []string{"defense-impairment"}},
	"T1580":     {Name: "Cloud Infrastructure Discovery", Tactics: []string{"discovery"}},
	"T1583":     {Name: "Acquire Infrastructure", Tactics: []string{"resource-development"}},
	"T1583.001": {Name: "Domains", Tactics: []string{"resource-development"}},
	"T1583.002": {Name: "DNS Server", Tactics: []string{"resource-development"}},
	"T1583.003": {Name: "Virtual Private Server", Tactics: []string{"resource-development"}},
	"T1583.004": {Name: "Server", Tactics: []string{"resource-development"}},
	"T1583.005": {Name: "Botnet", Tactics: []string{"resource-development"}},
	"T1583.006": {Name: "Web Services", Tactics: []string{"resource-development"}},
	"T1583.007": {Name: "Serverless", Tactics: []string{"resource-development"}},
	"T1583.008": {Name: "Malvertising", Tactics: []string{"resource-development"}},
	"T1584":     {Name: "Compromise Infrastructure", Tactics: []string{"resource-development"}},
	"T1584.001": {Name: "Domains", Tactics: []string{"resource-development"}},
	"T1584.002": {Name: "DNS Server", Tactics: []string{"resource-development"}},
	"T1584.003": {Name: "Virtual Private Server", Tactics: []string{"resource-development"}},
	"T1584.004": {Name: "Server", Tactics: []string{"resource-development"}},
	"T1584.005": {Name: "Botnet", Tactics: []string{"resource-development"}},
	"T1584.006": {Name: "Web Services", Tactics: []string{"resource-development"}},
	"T1584.007": {Name: "Serverless", Tactics: []string{"resource-development"}},
	"T1584.008": {Name: "Network Devices", Tactics: []string{"resource-development"}},
	"T1585":     {Name: "Establish Accounts", Tactics: []string{"resource-development"}},
	"T1585.001": {Name: "Social Media Accounts", Tactics: []string{"resource-development"}},
	"T1585.002": {Name: "Email Accounts", Tactics: []string{"resource-development"}},
	"T1585.003": {Name: "Cloud Accounts", Tactics: []string{"resource-development"}},
	"T1586":     {Name: "Compromise Accounts", Tactics: []string{"resource-development"}},
	"T1586.001": {Name: "Social Media Accounts", Tactics: []string{"resource-development"}},
	"T1586.002": {Name: "Email Accounts", Tactics: []string{"resource-development"}},
	"T1586.003": {Name: "Cloud Accounts", Tactics: []string{"resource-development"}},
	"T1587":     {Name: "Develop Capabilities", Tactics: []string{"resource-development"}},
	"T1587.001": {Name: "Malware", Tactics: []string{"resource-development"}},
	"T1587.002": {Name: "Code Signing Certificates", Tactics: []string{"resource-development"}},
	"T1587.003": {Name: "Digital Certificates", Tactics: []string{"resource-development"}},
	"T1587.004": {Name: "Exploits", Tactics: []string{"resource-development"}},
	"T1588":     {Name: "Obtain Capabilities", Tactics: []string{"resource-development"}},
	"T1588.001": {Name: "Malware", Tactics: []string{"resource-development"}},
	"T1588.002": {Name: "Tool", Tactics: []string{"resource-development"}},
	"T1588.003": {Name: "Code Signing Certificates", Tactics: []string{"resource-development"}},
	"T1588.004": {Name: "Digital Certificates", Tactics: []string{"resource-development"}},
	"T1588.005": {Name: "Exploits", Tactics: []string{"resource-development"}},
	"T1588.006": {Name: "Vulnerabilities", Tactics: []string{"resource-development"}},
	"T1588.007": {Name: "Artificial Intelligence", Tactics: []string{"resource-development"}},
	"T1589":     {Name: "Gather Victim Identity Information", Tactics: []string{"reconnaissance"}},
	"T1589.001": {Name: "Credentials", Tactics: []string{"reconnaissance"}},
	"T1589.002": {Name: "Email Addresses", Tactics: []string{"reconnaissance"}},
	"T1589.003": {Name: "Employee Names", Tactics: []string{"reconnaissance"}},
	"T1590":     {Name: "Gather Victim Network Information", Tactics: []string{"reconnaissance"}},
	"T1590.001": {Name: "Domain Properties", Tactics: []string{"reconnaissance"}},
	"T1590.002": {Name: "DNS", Tactics: []string{"reconnaissance"}},
	"T1590.003": {Name: "Network Trust Dependencies", Tactics: []string{"reconnaissance"}},
	"T1590.004": {Name: "Network Topology", Tactics: []string{"reconnaissance"}},
	"T1590.005": {Name: "IP Addresses", Tactics: []string{"reconnaissance"}},
	"T1590.006": {Name: "Network Security Appliances", Tactics: []string{"reconnaissance"}},
	"T1591":     {Name: "Gather Victim Org Information", Tactics: []string{"reconnaissance"}},
	"T1591.001": {Name: "Determine Physical Locations", Tactics: []string{"reconnaissance"}},
	"T1591.002": {Name: "Business Relationships", Tactics: []string{"reconnaissance"}},
	"T1591.003": {Name: "Identify Business Tempo", Tactics: []string{"reconnaissance"}},
	"T1591.004": {Name: "Identify Roles", Tactics: []string{"reconnaissance"}},
	"T1592":     {Name: "Gather Victim Host Information", Tactics: []string{"reconnaissance"}},
	"T1592.001": {Name: "Hardware", Tactics: []string{"reconnaissance"}},
	"T1592.002": {Name: "Software", Tactics: []string{"reconnaissance"}},
	"T1592.003": {Name: "Firmware", Tactics: []string{"reconnaissance"}},
	"T1592.004": {Name: "Client Configurations", Tactics: []string{"reconnaissance"}},
	"T1593":     {Name: "Search Open Websites/Domains", Tactics: []string{"reconnaissance"}},
	"T1593.001": {Name: "Social Media", Tactics: []string{"reconnaissance"}},
	"T1593.002": {Name: "Search Engines", Tactics: []string{"reconnaissance"}},
	"T1593.003": {Name: "Code Repositories", Tactics: []string{"reconnaissance"}},
	"T1594":     {Name: "Search Victim-Owned Websites", Tactics: []string{"reconnaissance"}},
	"T1595":     {Name: "Active Scanning", Tactics: []string{"reconnaissance"}},
	"T1595.001": {Name: "Scanning IP Blocks", Tactics: []string{"reconnaissance"}},
	"T1595.002": {Name: "Vulnerability Scanning", Tactics: []string{"reconnaissance"}},
	"T1595.003": {Name: "Wordlist Scanning", Tactics: []string{"reconnaissance"}},
	"T1596":     {Name: "Search Open Technical Databases", Tactics: []string{"reconnaissance"}},
	"T1596.001": {Name: "DNS/Passive DNS", Tactics: []string{"reconnaissance"}},
	"T1596.002": {Name: "WHOIS", Tactics: []string{"reconnaissance"}},
	"T1596.003": {Name: "Digital Certificates", Tactics: []string{"reconnaissance"}},
	"T1596.004": {Name: "CDNs", Tactics: []string{"reconnaissance"}},
	"T1596.005": {Name: "Scan Databases", Tactics: []string{"reconnaissance"}},
	"T1597":     {Name: "Search Closed Sources", Tactics: []string{"reconnaissance"}},
	"T1597.001": {Name: "Threat Intel Vendors", Tactics: []string{"reconnaissance"}},
	"T1597.002": {Name: "Purchase Technical Data", Tactics: []string{"reconnaissance"}},
	"T1598":     {Name: "Phishing for Information", Tactics: []string{"reconnaissance"}},
	"T1598.001": {Name: "Spearphishing Service", Tactics: []string{"reconnaissance"}},
	"T1598.002": {Name: "Spearphishing Attachment", Tactics: []string{"reconnaissance"}},
	"T1598.003": {Name: "Spearphishing Link", Tactics: []string{"reconnaissance"}},
	"T1598.004": {Name: "Spearphishing Voice", Tactics: []string{"reconnaissance"}},
	"T1599":     {Name: "Network Boundary Bridging", Tactics: []string{"defense-impairment"}},
	"T1599.001": {Name: "Network Address Translation Traversal", Tactics: []string{"defense-impairment"}},
	"T1600":     {Name: "Weaken Encryption", Tactics: []string{"defense-impairment"}},
	"T1600.001": {Name: "Reduce Key Space", Tactics: []string{"defense-impairment"}},
	"T1600.002": {Name: "Disable Crypto Hardware", Tactics: []string{"defense-impairment"}},
	"T1601":     {Name: "Modify System Image", Tactics: []string{"defense-impairment"}},
	"T1601.001": {Name: "Patch System Image", Tactics: []string{"defense-impairment"}},
	"T1601.002": {Name: "Downgrade System Image", Tactics: []string{"defense-impairment"}},
	"T1602":     {Name: "Data from Configuration Repository", Tactics: []string{"collection"}},
	"T1602.001": {Name: "SNMP (MIB Dump)", Tactics: []string{"collection"}},
	"T1602.002": {Name: "Network Device Configuration Dump", Tactics: []string{"collection"}},
	"T1606":     {Name: "Forge Web Credentials", Tactics: []string{"credential-access"}},
	"T1606.001": {Name: "Web Cookies", Tactics: []string{"credential-access"}},
	"T1606.002": {Name: "SAML Tokens", Tactics: []string{"credential-access"}},
	"T1608":     {Name: "Stage Capabilities", Tactics: []string{"resource-development"}},
	"T1608.001": {Name: "Upload Malware", Tactics: []string{"resource-development"}},
	"T1608.002": {Name: "Upload Tool", Tactics: []string{"resource-development"}},
	"T1608.003": {Name: "Install Digital Certificate", Tactics: []string{"resource-development"}},
	"T1608.004": {Name: "Drive-by Target", Tactics: []string{"resource-development"}},
	"T1608.005": {Name: "Link Target", Tactics: []string{"resource-development"}},
	"T1608.006": {Name: "SEO Poisoning", Tactics: []string{"resource-development"}},
	"T1609":     {Name: "Container Administration Command", Tactics: []string{"execution"}},
	"T1610":     {Name: "Deploy Container", Tactics: []string{"execution"}},
	"T1611":     {Name: "Escape to Host", Tactics: []string{"privilege-escalation"}},
	"T1612":     {Name: "Build Image on Host", Tactics: []string{"stealth"}},
	"T1613":     {Name: "Container and Resource Discovery", Tactics: []string{"discovery"}},
	"T1614":     {Name: "System Location Discovery", Tactics: []string{"discovery"}},
	"T1614.001": {Name: "System Language Discovery", Tactics: []string{"discovery"}},
	"T1615":     {Name: "Group Policy Discovery", Tactics: []string{"discovery"}},
	"T1619":     {Name: "Cloud Storage Object Discovery", Tactics: []string{"discovery"}},
	"T1620":     {Name: "Reflective Code Loading", Tactics: []string{"stealth"}},
	"T1621":     {Name: "Multi-Factor Authentication Request Generation", Tactics: []string{"credential-access"}},
	"T1622":     {Name: "Debugger Evasion", Tactics: []string{"discovery", "stealth"}},
	"T1647":     {Name: "Plist File Modification", Tactics: []string{"defense-impairment"}},
	"T1648":     {Name: "Serverless Execution", Tactics: []string{"execution"}},
	"T1649":     {Name: "Steal or Forge Authentication Certificates", Tactics: []string{"credential-access"}},
	"T1650":     {Name: "Acquire Access", Tactics: []string{"resource-development"}},
	"T1651":     {Name: "Cloud Administration Command", Tactics: []string{"execution"}},
	"T1652":     {Name: "Device Driver Discovery", Tactics: []string{"discovery"}},
	"T1653":     {Name: "Power Settings", Tactics: []string{"persistence"}},
	"T1654":     {Name: "Log Enumeration", Tactics: []string{"discovery"}},
	"T1656":     {Name: "Impersonation", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1684.001"},
	"T1657":     {Name: "Financial Theft", Tactics: []string{"impact"}},
	"T1659":     {Name: "Content Injection", Tactics: []string{"command-and-control", "initial-access"}},
	"T1665":     {Name: "Hide Infrastructure", Tactics: []string{"command-and-control"}},
	"T1666":     {Name: "Modify Cloud Resource Hierarchy", Tactics: []string{"defense-impairment"}},
	"T1667":     {Name: "Email Bombing", Tactics: []string{"impact"}},
	"T1668":     {Name: "Exclusive Control", Tactics: []string{"persistence"}},
	"T1669":     {Name: "Wi-Fi Networks", Tactics: []string{"initial-access"}},
	"T1671":     {Name: "Cloud Application Integration", Tactics: []string{"persistence"}},
	"T1672":     {Name: "Email Spoofing", Tactics: []string{"stealth"}, Revoked: true, Replacement: "T1684.002"},
	"T1673":     {Name: "Virtual Machine Discovery", Tactics: []string{"discovery"}},
	"T1674":     {Name: "Input Injection", Tactics: []string{"execution"}},
	"T1675":     {Name: "ESXi Administration Command", Tactics: []string{"execution"}},
	"T1677":     {Name: "Poisoned Pipeline Execution", Tactics: []string{"execution"}},
	"T1678":     {Name: "Delay Execution", Tactics: []string{"stealth"}},
	"T1679":     {Name: "Selective Exclusion", Tactics: []string{"stealth"}},
	"T1680":     {Name: "Local Storage Discovery", Tactics: []string{"discovery"}},
	"T1681":     {Name: "Search Threat Vendor Data", Tactics: []string{"reconnaissance"}},
	"T1682":     {Name: "Query Public AI Services", Tactics: []string{"reconnaissance"}},
	"T1683":     {Name: "Generate Content", Tactics: []string{"resource-development"}},
	"T1683.001": {Name: "Written Content", Tactics: []string{"resource-development"}},
	"T1683.002": {Name: "Audio-Visual Content", Tactics: []string{"resource-development"}},
	"T1684":     {Name: "Social Engineering", Tactics: []string{"stealth"}},
	"T1684.001": {Name: "Impersonation", Tactics: []string{"stealth"}},
	"T1684.002": {Name: "Email Spoofing", Tactics: []string{"stealth"}},
	"T1685":     {Name: "Disable or Modify Tools", Tactics: []string{"defense-impairment"}},
	"T1685.001": {Name: "Disable or Modify Windows Event Log", Tactics: []string{"defense-impairment"}},
	"T1685.002": {Name: "Disable or Modify Cloud Log", Tactics: []string{"defense-impairment"}},
	"T1685.003": {Name: "Modify or Spoof Tool UI", Tactics: []string{"defense-impairment"}},
	"T1685.004": {Name: "Disable or Modify Linux Audit System Log", Tactics: []string{"defense-impairment"}},
	"T1685.005": {Name: "Clear Windows Event Logs", Tactics: []string{"defense-impairment"}},
	"T1685.006": {Name: "Clear Linux or Mac System Logs", Tactics: []string{"defense-impairment"}},
	"T1686":     {Name: "Disable or Modify System Firewall", Tactics: []string{"defense-impairment"}},
	"T1686.001": {Name: "Cloud Firewall", Tactics: []string{"defense-impairment"}},
	"T1686.002": {Name: "Network Device Firewall", Tactics: []string{"defense-impairment"}},
	"T1686.003": {Name: "Windows Host Firewall", Tactics: []string{"defense-impairment"}},
	"T1687":     {Name: "Exploitation for Defense Impairment", Tactics: []string{"defense-impairment"}},
	"T1688":     {Name: "Safe Mode Boot", Tactics: []string{"defense-impairment"}},
	"T1689":     {Name: "Downgrade Attack", Tactics: []string{"defense-impairment"}},
	"T1690":     {Name: "Prevent Command History Logging", Tactics: []string{"defense-impairment"}},
}
